-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'America/New_York';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notifyHourLocal" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastPushLocalDay" TEXT;
